version: "3.7"
services:
  larave-owl-gta5:
    build: .
    container_name: laravel-owl-gta5
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    command: >
        sh -c "chown -R www-data:www-data /var/www/storage /var/www/bootstrap/cache &&
               chmod -R 775 /var/www/storage /var/www/bootstrap/cache &&
               php-fpm"
    networks:
      - laravel-owl-gta5-network

  nginx:
    image: nginx:alpine
    container_name: laravel-owl-gta5-nginx
    restart: unless-stopped
    ports:
       - "80:80"
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - laravel-owl-gta5-network

networks:
  laravel-owl-gta5-network:
    driver: bridge
